"""Local setup paths, env files, and email-report config for ./setup.sh."""

from __future__ import annotations

import os
import stat
import tomllib
from dataclasses import dataclass
from pathlib import Path

from .setup_workflow import DEFAULT_WORKFLOW_CONFIG, workflow_path

DEFAULT_ENV_FILE = ".env.email-report"
DEFAULT_CONFIG_DIR = ".github-usage"
DEFAULT_CONFIG_FILE = "config.toml"
ENV_EXAMPLE = ".env.email-report.example"
CONFIG_EXAMPLE = ".github-usage/config.example.toml"

SECRET_ENV_KEYS = ("GITHUB_TOKEN", "RESEND_API_KEY", "REPORT_EMAIL", "RESEND_FROM")
OPTIONAL_ENV_KEYS = ("REPORT_SUBJECT", "GITHUB_USAGE_ENV_FILE", "GITHUB_USAGE_LOG_DIR")

DEFAULT_EMAIL_REPORT = {
    "include_consumers": False,
    "include_artifact_storage": False,
    "include_release_assets": False,
    "max_repos": 100,
    "warn_over": ["25", "80%"],
    "skip_actions": False,
    "skip_copilot": False,
    "skip_lfs": False,
}

DEFAULT_SCHEDULE = {
    "weekday": 1,
    "hour": 9,
    "minute": 0,
}


@dataclass
class SetupPaths:
    """Resolved paths for local setup artifacts."""

    root: Path
    env_file: Path
    config_dir: Path
    config_file: Path
    launchd_dir: Path
    launchd_plist: Path

    @classmethod
    def from_root(cls, root: Path | None = None) -> SetupPaths:
        base = (root or repo_root()).resolve()
        config_dir = base / DEFAULT_CONFIG_DIR
        return cls(
            root=base,
            env_file=Path(os.environ.get("GITHUB_USAGE_ENV_FILE", base / DEFAULT_ENV_FILE)),
            config_dir=config_dir,
            config_file=config_dir / DEFAULT_CONFIG_FILE,
            launchd_dir=config_dir / "launchd",
            launchd_plist=config_dir / "launchd" / "com.github.github-usage.email-report.plist",
        )


def repo_root() -> Path:
    """Return the repository root (parent of src/github_usage)."""
    return Path(__file__).resolve().parents[2]


def mask_secret(value: str) -> str:
    """Return a safe display form for a secret value."""
    value = value.strip()
    if not value:
        return "(not set)"
    if len(value) <= 4:
        return "***"
    return f"{value[:2]}...{value[-2:]}"


def read_env_file(path: Path) -> dict[str, str]:
    """Parse a shell env file into key/value pairs."""
    if not path.is_file():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        if line.startswith("export "):
            line = line[len("export ") :].strip()
        if "=" not in line:
            continue
        key, raw = line.split("=", 1)
        key = key.strip()
        value = raw.strip()
        if len(value) >= 2 and value[0] == value[-1] and value[0] in "\"'":
            quote = value[0]
            value = value[1:-1]
            if quote == '"':
                value = _unescape_env_value(value)
        values[key] = value
    return values


def write_env_file(path: Path, values: dict[str, str]) -> None:
    """Write a shell env file with restrictive permissions."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by github-usage setup. Do not commit this file.",
        "# Contains secrets for local email reports and scheduled runs.",
        "",
    ]
    for key in (*SECRET_ENV_KEYS, *OPTIONAL_ENV_KEYS):
        if key in values and values[key].strip():
            lines.append(f'export {key}="{_escape_env_value(values[key])}"')
    path.write_text("\n".join(lines) + "\n", encoding="utf-8")
    path.chmod(stat.S_IRUSR | stat.S_IWUSR)


def _escape_env_value(value: str) -> str:
    return value.replace("\\", "\\\\").replace('"', '\\"')


def _unescape_env_value(value: str) -> str:
    return value.replace('\\"', '"').replace("\\\\", "\\")


def load_config(path: Path) -> dict:
    """Load config.toml or return defaults."""
    if not path.is_file():
        return {
            "email_report": dict(DEFAULT_EMAIL_REPORT),
            "schedule": dict(DEFAULT_SCHEDULE),
            "github_actions": dict(DEFAULT_WORKFLOW_CONFIG),
        }
    data = tomllib.loads(path.read_text(encoding="utf-8"))
    email_report = {**DEFAULT_EMAIL_REPORT, **data.get("email_report", {})}
    schedule = {**DEFAULT_SCHEDULE, **data.get("schedule", {})}
    github_actions = {**DEFAULT_WORKFLOW_CONFIG, **data.get("github_actions", {})}
    return {"email_report": email_report, "schedule": schedule, "github_actions": github_actions}


def write_config(path: Path, config: dict) -> None:
    """Write config.toml from a nested dict."""
    path.parent.mkdir(parents=True, exist_ok=True)
    email = {**DEFAULT_EMAIL_REPORT, **config.get("email_report", {})}
    schedule = {**DEFAULT_SCHEDULE, **config.get("schedule", {})}
    ga = {**DEFAULT_WORKFLOW_CONFIG, **config.get("github_actions", {})}
    warn_over = email.get("warn_over") or []
    if isinstance(warn_over, str):
        warn_over = [warn_over]
    warn_lines = "\n".join(f'  "{item}",' for item in warn_over)
    text = f"""# Generated by github-usage setup. Safe to edit locally; do not commit secrets here.

[email_report]
include_consumers = {_bool(email.get("include_consumers"))}
include_artifact_storage = {_bool(email.get("include_artifact_storage"))}
include_release_assets = {_bool(email.get("include_release_assets"))}
max_repos = {int(email.get("max_repos", 100))}
warn_over = [
{warn_lines}
]
skip_actions = {_bool(email.get("skip_actions"))}
skip_copilot = {_bool(email.get("skip_copilot"))}
skip_lfs = {_bool(email.get("skip_lfs"))}

[schedule]
weekday = {int(schedule.get("weekday", 1))}
hour = {int(schedule.get("hour", 9))}
minute = {int(schedule.get("minute", 0))}

[github_actions]
cron = "{ga.get("cron", DEFAULT_WORKFLOW_CONFIG["cron"])}"
include_consumers = {_bool(ga.get("include_consumers"))}
include_artifact_storage = {_bool(ga.get("include_artifact_storage"))}
include_release_assets = {_bool(ga.get("include_release_assets"))}
"""
    path.write_text(text, encoding="utf-8")


def _bool(value: object) -> str:
    return "true" if bool(value) else "false"


def email_report_args(config: dict) -> list[str]:
    """Translate email_report config into CLI arguments."""
    email = {**DEFAULT_EMAIL_REPORT, **config.get("email_report", {})}
    args: list[str] = []
    if email.get("include_consumers"):
        args.append("--include-consumers")
    if email.get("include_artifact_storage"):
        args.append("--include-artifact-storage")
    if email.get("include_release_assets"):
        args.extend(["--include-release-assets", "--yes-include-release-assets"])
    max_repos = int(email.get("max_repos", 100))
    args.extend(["--max-repos", str(max_repos)])
    warn_over = email.get("warn_over") or []
    if isinstance(warn_over, str):
        warn_over = [warn_over]
    for threshold in warn_over:
        args.extend(["--warn-over", str(threshold)])
    if email.get("skip_actions"):
        args.append("--skip-actions")
    if email.get("skip_copilot"):
        args.append("--skip-copilot")
    if email.get("skip_lfs"):
        args.append("--skip-lfs")
    return args


def status_lines(paths: SetupPaths) -> list[str]:
    """Return human-readable setup status without printing secret values."""
    lines = [f"Repository root: {paths.root}"]
    env_exists = paths.env_file.is_file()
    lines.append(f"Env file ({paths.env_file.name}): {'present' if env_exists else 'missing'}")
    if env_exists:
        env_values = read_env_file(paths.env_file)
        for key in SECRET_ENV_KEYS:
            present = bool(env_values.get(key, "").strip())
            display = mask_secret(env_values.get(key, "")) if present else "(not set)"
            lines.append(f"  {key}: {display}")
    config_exists = paths.config_file.is_file()
    lines.append(
        f"Config file ({paths.config_file.relative_to(paths.root)}): "
        f"{'present' if config_exists else 'missing'}"
    )
    if config_exists:
        config = load_config(paths.config_file)
        email = config["email_report"]
        schedule = config["schedule"]
        ga = config.get("github_actions", {})
        lines.append(f"  max_repos: {email.get('max_repos')}")
        lines.append(
            "  optional sections: "
            f"consumers={email.get('include_consumers')}, "
            f"artifact_storage={email.get('include_artifact_storage')}, "
            f"release_assets={email.get('include_release_assets')}"
        )
        lines.append(
            f"  schedule: weekday={schedule.get('weekday')} "
            f"{schedule.get('hour'):02d}:{schedule.get('minute'):02d} local"
        )
        if ga:
            cron = ga.get("cron", DEFAULT_WORKFLOW_CONFIG["cron"])
            wf_status = "present" if workflow_path(paths.root).is_file() else "missing"
            lines.append(f"  GitHub Actions cron: {cron} (workflow file: {wf_status})")
        else:
            lines.append("  GitHub Actions: not configured")
    plist_exists = paths.launchd_plist.is_file()
    lines.append(f"LaunchAgent plist: {'generated' if plist_exists else 'not generated'}")
    return lines


def is_minimally_configured(paths: SetupPaths) -> bool:
    """Return True when env secrets and config exist."""
    if not paths.config_file.is_file():
        return False
    env_values = read_env_file(paths.env_file)
    return all(env_values.get(key, "").strip() for key in SECRET_ENV_KEYS)
